### ISSUE TITLE
[Suggestion] Reduce lag when loading world with elytras and Trident.

### ISSUE THREAD

**Issue by marlon-omc** [PluginBugs/Issues-ServerBooster#47]
the option of being able to configure a time of use for the **elytras** and **trident** as in the **NoChunkLag** plugin and with the option to deactivate the use of elytras and pitchforks when the tps go down and reactivate when the tps remain stable .

**Comment by LoneDev6** [comment]
implemented in the new upcoming update 1.0.57

```yml
elytra-optimize:
  reptide-trident-nerf:
    enabled: true
    delay: 60
  firework-nerf:
    enabled: true
    delay: 20
  log: false
  worlds:
    - world
    - world_nether
    - world_the_end
```

## Showcase
In the video I'm trying to continuously trigger the trident but I can't because of the cooldown.

https://user-images.githubusercontent.com/27242001/146191290-873e5209-cd40-4d77-962a-c45e41036663.mp4
